CREATE TABLE FRUTAS (
      ID INT NOT NULL IDENTITY PRIMARY KEY,
      NOME VARCHAR(50)  NOT NULL,
      MEDIDA VARCHAR(50),
      QUANTIDADE INT,
      VALIDADE DATETIME,
      PRECO MONEY,
      DESCRICAO VARCHAR (255)
)